title: blogs
email: blogs@replies.catskull.net
description: >- # this means to ignore newlines until "baseurl:"
  Blogging like it's 1999.
baseurl: "" # the subpath of your site, e.g. /blog
url: "blogs.catskull.net" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  catskull

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  blogs:
    output: true
    permalink: /:path

defaults:
  - scope:
      type: blogs
    values:
      layout: blog
